#Copyright (c) 2013-2022, Bartosz Taudul <wolf@nereid.pl>
#All rights reserved.

all: debug

debug:
	@+make -f debug.mk all

release:
	@+make -f release.mk all

clean:
	@+make -f build.mk clean

.PHONY: all clean debug release
